[package]
name = "seaki-daemon"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Daemon process and frontend API for Seaki"
repository = "https://github.com/normanpong/seaki"
readme = "../../README.md"
keywords = ["seaki", "wiki", "local-first"]
categories = ["development-tools"]

[lib]
path = "src/lib.rs"

[dependencies]
seaki-core = { path = "../seaki-core" }
seaki-pipe = { path = "../seaki-pipe" }
serde_json.workspace = true

[dev-dependencies]
seaki-channel = { path = "../seaki-channel" }
seaki-index = { path = "../seaki-index" }

