pub use seaki_dto::SCHEMA_VERSION;
use seaki_dto::{canonical_schema, INTERFACES, M0_DOMAIN_USE_CASE_METHODS, STRING_UNIONS};
use sha2::{Digest, Sha256};
use std::fmt::{self, Write};
use std::fs;
use std::path::{Path, PathBuf};

const HEADER: &str = r"// Generated by seaki-dto-codegen.
// Do not edit this file by hand. Run `pnpm dto:generate` instead.
";

#[derive(Debug)]
pub enum CodegenError {
    Io(std::io::Error),
    StaleGeneratedFile { path: PathBuf },
}

impl fmt::Display for CodegenError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Io(error) => write!(f, "{error}"),
            Self::StaleGeneratedFile { path } => write!(
                f,
                "generated DTO file is stale or schema hash mismatch: {}",
                path.display()
            ),
        }
    }
}

impl std::error::Error for CodegenError {}

impl From<std::io::Error> for CodegenError {
    fn from(value: std::io::Error) -> Self {
        Self::Io(value)
    }
}

pub type CodegenResult<T> = Result<T, CodegenError>;

#[must_use]
pub fn schema_hash() -> String {
    let digest = Sha256::digest(canonical_schema().as_bytes());
    hex_lower(&digest)
}

#[must_use]
pub fn generate_typescript() -> String {
    let mut output = String::new();
    output.push_str(HEADER);
    output.push('\n');
    writeln!(
        output,
        "export const SCHEMA_VERSION = {SCHEMA_VERSION} as const;"
    )
    .unwrap();
    write!(
        output,
        "export const SCHEMA_HASH =\n  \"{}\" as const;\n\n",
        schema_hash()
    )
    .unwrap();

    for string_union in STRING_UNIONS {
        let variants = string_union
            .variants
            .iter()
            .map(|variant| format!("\"{variant}\""))
            .collect::<Vec<_>>();
        let single_line = format!(
            "export type {} = {};",
            string_union.name,
            variants.join(" | ")
        );

        if single_line.len() <= 100 {
            output.push_str(&single_line);
            output.push_str("\n\n");
        } else {
            writeln!(output, "export type {} =", string_union.name).unwrap();
            for (index, variant) in variants.iter().enumerate() {
                output.push_str("  | ");
                output.push_str(variant);
                if index + 1 == variants.len() {
                    output.push_str(";\n\n");
                } else {
                    output.push('\n');
                }
            }
        }
    }

    for interface in INTERFACES {
        output.push_str("export interface ");
        output.push_str(interface.name);
        if let Some(generic) = interface.generic {
            output.push_str(generic);
        }
        output.push_str(" {\n");
        for field in interface.fields {
            output.push_str("  ");
            output.push_str(field.name);
            if field.optional {
                output.push('?');
            }
            output.push_str(": ");
            output.push_str(field.ts_type);
            output.push_str(";\n");
        }
        output.push_str("}\n\n");
    }

    output.push_str("export const M0_DOMAIN_USE_CASE_METHODS = {\n");
    for method in M0_DOMAIN_USE_CASE_METHODS {
        output.push_str("  ");
        output.push_str(method.key);
        output.push_str(": \"");
        output.push_str(method.value);
        output.push_str("\",\n");
    }
    output.push_str("} as const;\n\n");
    output.push_str(
        "export type M0DomainUseCaseMethod =\n  (typeof M0_DOMAIN_USE_CASE_METHODS)[keyof typeof M0_DOMAIN_USE_CASE_METHODS];\n",
    );
    output.push_str("\nexport const METHOD = M0_DOMAIN_USE_CASE_METHODS;\n");

    output
}

pub fn write_generated_file(path: impl AsRef<Path>) -> CodegenResult<()> {
    let path = path.as_ref();
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, generate_typescript())?;
    Ok(())
}

pub fn check_generated_file(path: impl AsRef<Path>) -> CodegenResult<()> {
    let path = path.as_ref();
    let expected = generate_typescript();
    let actual = fs::read_to_string(path)?;
    if actual == expected {
        Ok(())
    } else {
        Err(CodegenError::StaleGeneratedFile {
            path: path.to_path_buf(),
        })
    }
}

fn hex_lower(bytes: &[u8]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut output = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        output.push(HEX[(byte >> 4) as usize] as char);
        output.push(HEX[(byte & 0x0f) as usize] as char);
    }
    output
}

#[cfg(test)]
mod tests;
