// Generated by seaki-dto-codegen.
// Do not edit this file by hand. Run `pnpm dto:generate` instead.

export const SCHEMA_VERSION = 1 as const;
export const SCHEMA_HASH =
  "df22bc5470cd33f6f37f660548c6c2fe1e29ef3ffccdf8b750f6224867227273" as const;

export type IndexStatusState = "idle" | "indexing" | "fresh" | "stale" | "error";

export type DaemonConnectionStatus =
  | "daemon.connecting"
  | "daemon.ready"
  | "daemon.unavailable"
  | "daemon.error";

export type ImportStage =
  | "approval_pending"
  | "capability_denied"
  | "committed"
  | "denied"
  | "failed"
  | "grant_requested"
  | "granted"
  | "index_stale"
  | "indexed"
  | "parse_running"
  | "parsed"
  | "partial"
  | "patch_proposed"
  | "raw_committed"
  | "selected";

export type ApprovalStatus =
  | "pending"
  | "approved"
  | "applying"
  | "committed"
  | "rejected"
  | "expired"
  | "conflict";

export interface IndexStatusDTO {
  state: IndexStatusState;
  last_good_revision: string | null;
  stale_reason: string | null;
  updated_at: string | null;
}

export interface SourceRangeDTO {
  unit: "byte" | "line" | "page" | "anchor";
  start: number;
  end: number;
  label: string | null;
}

export interface WorkspaceDTO {
  workspace_id: string;
  root_uri: string;
  state: "empty" | "ready" | "degraded" | "audit_readonly";
  current_revision: string;
  audit_head: string;
  index_status: IndexStatusDTO;
}

export interface UserSelectedFileDTO {
  selection_id: string;
  display_name: string;
  platform: "electron";
  opaque_file_ref: string;
  declared_size: number;
  declared_mime: string;
}

export interface CapabilityGrantRequestDTO {
  operation: string;
  target: string;
  ttl: number;
  uses: number;
  reason: string;
  risk_summary: string;
}

export interface SourceManifestDTO {
  source_id: string;
  origin_display: string;
  mime: string;
  size: number;
  parse_status: ImportStage;
  permission_scope: string;
}

export interface CitationRefDTO {
  citation_id: string;
  source_id: string;
  range: SourceRangeDTO;
  wiki_page_id: string;
  claim_id: string;
  degraded_reason: string | null;
}

export interface SourceCardDTO {
  source_id: string;
  title: string;
  origin_display: string;
  range: SourceRangeDTO;
  summary: string;
  visibility: "visible" | "restricted" | "tombstoned";
  citation_refs: readonly CitationRefDTO[];
}

export interface AnnotationDTO {
  annotation_id: string;
  source_id: string;
  range: SourceRangeDTO;
  note: string;
  created_by: string;
  created_at: string;
  supersede_of: string | null;
  conflict_status: string | null;
}

export interface RiskSummaryDTO {
  level: "low" | "medium" | "high" | "critical";
  summary: string;
  factors: readonly string[];
  requires_manual_approval: boolean;
}

export interface PatchDiffDTO {
  format: "unified" | "structured";
  text: string;
  affected_paths: readonly string[];
  added_lines: number;
  removed_lines: number;
}

export interface CitationEvidenceDTO {
  citation_id: string;
  source_id: string;
  source_title: string;
  range: SourceRangeDTO;
  cited_ranges: readonly SourceRangeDTO[];
  excerpt: string;
  visibility: "visible" | "restricted" | "tombstoned";
  degraded_reason: string | null;
}

export interface CitationValidationDTO {
  citation_id: string;
  claim_id?: string | null;
  state: "valid" | "invalid" | "degraded";
  reason: string | null;
  evidence?: readonly CitationEvidenceDTO[];
  cited_ranges?: readonly SourceRangeDTO[];
  taint_flags?: readonly string[];
  security_flags?: readonly string[];
}

export interface ClaimReviewDTO {
  claim_id: string;
  page_id: string;
  text: string;
  citation_ids: readonly string[];
  citation_validation: readonly CitationValidationDTO[];
  risk_summary: RiskSummaryDTO;
  taint_flags: readonly string[];
  security_flags: readonly string[];
}

export interface WikiPatchProposalDTO {
  patch_id: string;
  base_revision: string;
  diff: string | PatchDiffDTO;
  claim_ids: readonly string[];
  claims?: readonly ClaimReviewDTO[];
  citation_validation: readonly CitationValidationDTO[];
  risk_summary: string | RiskSummaryDTO;
  taint_flags?: readonly string[];
  security_flags?: readonly string[];
}

export interface ApprovalClaimDecisionDTO {
  claim_id: string;
  decision: "approve" | "reject";
  reason: string | null;
  decided_by: string | null;
  decided_at: string | null;
}

export interface ApprovalRequestDTO {
  approval_id: string;
  patch_id: string;
  status?: ApprovalStatus;
  required_by: string;
  expires_at: string;
  policy_decision: "allow" | "deny" | "requires_approval";
  proposal?: WikiPatchProposalDTO;
  claim_decisions?: readonly ApprovalClaimDecisionDTO[];
  rejection_reason?: string | null;
  wal_entry_id?: string | null;
  audit_id?: string | null;
}

export interface ApprovalReviewDTO {
  request: ApprovalRequestDTO;
  proposal: WikiPatchProposalDTO;
}

export interface ApprovalDecisionResultDTO {
  approval_id: string;
  patch_id: string;
  status: ApprovalStatus;
  claim_decisions: readonly ApprovalClaimDecisionDTO[];
  rejection_reason: string | null;
  wal_entry_id: string | null;
  audit_id: string | null;
  transaction_id: string | null;
  committed_revision: string | null;
  denied_reason: string | null;
}

export interface SearchResultDTO {
  result_id: string;
  kind: "wiki_page" | "claim" | "source";
  title: string;
  snippet: string | null;
  citation_refs: readonly CitationRefDTO[];
  index_status: IndexStatusDTO;
}

export interface ChannelAnswerDTO {
  message_id: string;
  thread_id: string;
  audit_id: string;
  transaction_id: string;
  citation_ids: readonly string[];
}

export interface OutboxItemDTO {
  outbox_id: string;
  transaction_id: string;
  state: "pending" | "sent" | "failed";
  provider_idempotency_key: string;
  attempt_count: number;
  next_attempt_at: string | null;
}

export interface FrontendEventEnvelope<TPayload = unknown> {
  event_id: string;
  schema_version: typeof SCHEMA_VERSION;
  payload_schema_hash: string;
  seq: number;
  workspace_id: string;
  actor_id: string;
  scope: string;
  task_id?: string;
  transaction_id?: string;
  correlation_id: string;
  causation_id?: string;
  revision: string;
  occurred_at: string;
  replayable: boolean;
  idempotency_key: string;
  type: string;
  payload: TPayload;
}

export const M0_DOMAIN_USE_CASE_METHODS = {
  WORKSPACE_INIT: "workspace.init",
  FILES_PREPARE_USER_SELECTED: "files.prepareUserSelected",
  SOURCE_INGEST_SELECTED_FILE: "source.ingestSelectedFile",
  APPROVAL_REVIEW_PATCH: "approval.reviewPatch",
  APPROVAL_DECIDE: "approval.decide",
  WIKI_READ_PAGE: "wiki.readPage",
  SEARCH_QUERY: "search.query",
  CITATION_RESOLVE: "citation.resolve",
} as const;

export type M0DomainUseCaseMethod =
  (typeof M0_DOMAIN_USE_CASE_METHODS)[keyof typeof M0_DOMAIN_USE_CASE_METHODS];

export const METHOD = M0_DOMAIN_USE_CASE_METHODS;
